# QUESTION 1

In [1]:
# Create a NumPy array of shape (5, 5) filled with random integers between 10 and 50. Write a function that replaces all even numbers in the array with -1.

import numpy as np

def replace_even_with_minus_one(arr):
  arr[arr % 2 == 0] = -1
  return arr

random_array = np.random.randint(10, 51, size=(5, 5))
print("Original Array:\n", random_array)

modified_array = replace_even_with_minus_one(random_array)
print("\nModified Array:\n", modified_array)


Original Array:
 [[43 42 46 25 42]
 [13 11 28 43 27]
 [28 33 43 33 44]
 [13 47 18 37 46]
 [15 40 43 35 34]]

Modified Array:
 [[43 -1 -1 25 -1]
 [13 11 -1 43 27]
 [-1 33 43 33 -1]
 [13 47 -1 37 -1]
 [15 -1 43 35 -1]]


# QUESTION 2

In [17]:

def categorize_students(filepath):
    """
    Categorizes students based on their scores and returns a dictionary of categories.

    Args:
        filepath: The path to the text file containing student data.

    Returns:
        A dictionary where keys are categories and values are lists of student names.
        Returns an empty dictionary if the file is not found or an error occurs.
    """
    try:
        categories = {"Excellent": [], "Average": [], "Needs Improvement": []}
        with open(filepath, 'r') as file:
            for line in file:
                try:
                    name, score_str = line.strip().split(',')
                    score = int(score_str)

                    if score >= 80:
                        categories["Excellent"].append(name)
                    elif 50 <= score <= 79:
                        categories["Average"].append(name)
                    else:
                        categories["Needs Improvement"].append(name)
                except ValueError:
                    print(f"Skipping invalid line: {line.strip()}")
        return categories
    except FileNotFoundError:
        print(f"Error: File not found at {filepath}")
        return {}
    except Exception as e:
        print(f"An error occurred: {e}")
        return {}

filepath = 'student_scores.txt'
student_categories = categorize_students(filepath)

if student_categories:
    for category, students in student_categories.items():
        print(f"{category}: {', '.join(students)}")

Excellent: Alice, David
Average: Bob, Eve
Needs Improvement: Charlie


# QUESTION 3

In [24]:
from google.colab import files

uploaded = files.upload()


Saving Products.txt to Products.txt


In [25]:
purchased_products, remaining_budget = calculate_products_within_budget("/path/to/your/Products.txt", 100)
print("Purchased Products:", purchased_products)
print("Remaining Budget:", remaining_budget)


Error: File '/path/to/your/Products.txt' not found.
Purchased Products: []
Remaining Budget: 100


In [26]:
def calculate_products_within_budget(filename, budget):
    """
    Calculate products that can be bought within a given budget from a file.

    :param filename: str - Name of the file containing product details (product name and price).
    :param budget: float - Available budget.
    :return: tuple - (list of purchased products, remaining budget).
    """
    purchased_products = []
    remaining_budget = budget

    try:
        # Open and read the file
        with open(filename, 'r') as file:
            for line in file:
                # Split the line into product name and price
                product_data = line.strip().split()
                if len(product_data) != 2:
                    continue  # Skip lines that don't have exactly two elements

                product_name, price_str = product_data
                try:
                    price = float(price_str)
                except ValueError:
                    continue  # Skip invalid price entries

                # Add the product if it fits in the remaining budget
                if price <= remaining_budget:
                    purchased_products.append(product_name)
                    remaining_budget -= price

        return purchased_products, remaining_budget
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return [], budget
    except Exception as e:
        print(f"An error occurred: {e}")
        return [], budget


# Example Usage
filename = "products.txt"  # Replace with the path to your file
budget = 100  # Replace with your desired budget
products, balance = calculate_products_within_budget(filename, budget)

print("Products Purchased:", products)
print("Remaining Budget:", balance)


Error: File 'products.txt' not found.
Products Purchased: []
Remaining Budget: 100
